FROM %%ORG%%/base:%%TAG%%
MAINTAINER The Dockbit Team "team@dockbit.com"

# Install AWS CLI via pip
WORKDIR /tmp
COPY components/aws_cli.sh ./
RUN ./aws_cli.sh

# Cleanup & execution environment
USER root
RUN rm -f aws_cli.sh
COPY docker-entrypoint.sh /docker-entrypoint.sh
USER dockbit
WORKDIR /home/dockbit
ENTRYPOINT ["/docker-entrypoint.sh"]